### ISSUE TITLE
Problem while reading a package name that contains dots

### ISSUE THREAD

**Issue by racembs** [rodhilton/jasome#9] opened 2019-03-29 10:06 UTC
Exception in thread "main" java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at org.jasome.input.Scanner.configureParserAndResolver(Scanner.java:100)
        at org.jasome.input.Scanner.doScan(Scanner.java:25)
        at org.jasome.input.FileScanner.scan(FileScanner.java:47)
        at org.jasome.executive.CommandLineExecutive.main(CommandLineExecutive.java:70)

**Comment by rodhilton** [comment] 2020-01-22 04:42
Seems like a dupe of #10

**Closed as completed by rodhilton** 2020-01-22 04:42 UTC
